baseurl = "https://emunix.org/"
languageCode = "ru"
title = "Emunix"
disqusShortname = "emunix"
pygmentsCodeFences = true
PygmentsStyle = "monokailight"

[params]
    # my theme is angels-ladder
    copyright = "© 2011-2018, <a href=\"mailto:btimofeev@emunix.org\">Борис Тимофеев</a>"
    twitter = "https://twitter.com/btimofeev"
    github = "https://github.com/btimofeev"
    # subtitle = "Linux, эмуляция, программирование."
    # facebook = "https://facebook.com/foobar"
    # profile = "/images/profile.png"
    analytics = "UA-28744527-1"
